#
# Copyright (C) 2013-2018 Draios Inc dba Sysdig.
#
# This file is part of sysdig .
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
language: c

matrix:
  include:
    - env: BUILD_TYPE=Debug
      os: linux
    - env: BUILD_TYPE=Release
      os: linux
    - env: BUILD_TYPE=Debug
      os: osx
    - env: BUILD_TYPE=Release
      os: osx
    - env: BUILD_TYPE=Debug
      os: linux
      arch: ppc64le
      dist: bionic
    - env: BUILD_TYPE=Release
      os: linux
      arch: ppc64le
      dist: bionic
    - env: BUILD_TYPE=Debug
      os: linux
      arch: s390x
      dist: bionic
    - env: BUILD_TYPE=Release
      os: linux
      arch: s390x
      dist: bionic    

sudo: required
services:
    - docker
before_install:
    - .travis-scripts/${TRAVIS_OS_NAME}/before_install.sh
install:
    - .travis-scripts/${TRAVIS_OS_NAME}/install.sh
before_script:
    - export KERNELDIR=/lib/modules/$(uname -r)/build
script:
    - .travis-scripts/${TRAVIS_OS_NAME}/build.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fdbc2356fb0ea2f15033
    on_success: change
    on_failure: always
    on_start: never
