language: c
env:
    - BUILD_TYPE=Debug NEW_CC=clang NEW_CXX=clang++
    - BUILD_TYPE=Release NEW_CC=clang NEW_CXX=clang++
    - BUILD_TYPE=Debug NEW_CC=gcc NEW_CXX=g++
    - BUILD_TYPE=Release NEW_CC=gcc NEW_CXX=g++
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install rpm linux-headers-generic gcc-4.5 g++-4.5 gcc-4.4 g++-4.4
    - sudo apt-get purge libncurses5-dev
before_script:
    - export KERNELDIR=/lib/modules/$(ls /lib/modules | sort | head -1)/build
script:
    - export CC=$NEW_CC
    - export CXX=$NEW_CXX
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - make VERBOSE=1
    - make package
    - cd ..
    - rm -rf build
    - pushd $(mktemp -d --tmpdir sysdig.XXXXXXXXXX)
    - wget http://download.draios.com/dependencies/zlib-1.2.8.tar.gz
    - tar -xzf zlib-1.2.8.tar.gz
    - cd zlib-1.2.8
    - ./configure
    - make
    - sudo make install
    - popd
    - rm -rf userspace/libsinsp/third-party/jsoncpp
    - sudo apt-get install libncurses5-dev libluajit-5.1-dev libjsoncpp-dev
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_BUNDLED_JSONCPP=OFF -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_ZLIB=OFF -DZLIB_PREFIX=/usr/local
    - make VERBOSE=1
    - make package
    - cd ..
    - test/sysdig_trace_regression.sh build/userspace/sysdig/sysdig build/userspace/sysdig/chisels $TRAVIS_BRANCH
